- title: WEB3 consulting
  description:  Obvious Ridge Route is one of the earliest full-stack dev shops in the web3 space.  
                Our team includes anon contributors with years of web3 experience developing defi protocols, DAOs, and NFT projects. 
                We recognize the efficiency and advantage of core dev teams in web3 that are in constant sync.

- title: Software development
  description:  ORR is a full-stack web and mobile development shop with 10+ of web2 experience and one of the earliest web3 dev shops.
                Let us make your ideas a reality from design to QA testing and deployment.

- title: UI/UX Design
  description:  Our team of experienced UI/UX designers and graphic artists 
                have worked on a variety of projects including enterprise software, 
                data visualization, digital content platforms, web3 defi and NFT projects, DAOs and more.

- title: Business process outsourcing
  description:  Our outsource business professionals have exceptional communication and organizational skills. 
                We provide a range of services including data entry, virtual assistants, customer and tech support, and more. 
                Our rates and quality of work are the best on earth.